FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04
WORKDIR /code
RUN apt-get update && apt-get install -y git ffmpeg
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . . 