version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes: [ .:/code ]
    environment: [ REDIS_URL=redis://redis:6379/0 ]
    ports: [ "8000:8000" ]
    depends_on: [ redis ]
  worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: celery -A app.tasks worker -Q video -l info
    volumes: [ .:/code ]
    environment: [ REDIS_URL=redis://redis:6379/0 ]
    depends_on: [ redis ]
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ] 